version: '3'

services:
  api-service:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    links: 
      - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3000
      - NODE_PATH=./src
    ports:
      - 3000:3000
    command: npm start
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    volumes:
      -  ./redis-data:/data
    